# Generated by Django 2.2.5 on 2019-09-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('LAB', 'LAB'), ('LECTURE', 'LECTURE')], max_length=20),
        ),
    ]
