# Generated by Django 2.2.5 on 2019-09-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0003_auto_20190930_0114'),
        ('rooms', '0002_auto_20190929_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='monday',
            field=models.ManyToManyField(to='scheduledClass.Scheduled'),
        ),
    ]
