# Generated by Django 2.2.5 on 2019-09-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rooms_monday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='monday',
        ),
    ]
