# Generated by Django 2.2.5 on 2019-09-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_rooms_monday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='monday',
        ),
    ]
