# Generated by Django 2.2.5 on 2019-10-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_rooms_monday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('LAB', 'LAB'), ('LECTURE', 'LECTURE'), ('WEB', 'WEB')], max_length=20),
        ),
    ]
