# Generated by Django 2.2.5 on 2019-10-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20191010_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('LAB', 'LAB'), ('LECTURE', 'LECTURE')], max_length=20),
        ),
    ]
