# Generated by Django 2.2.5 on 2019-09-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_number', models.IntegerField(unique=True)),
                ('subject', models.CharField(max_length=20)),
                ('min_hours', models.IntegerField()),
                ('max_hours', models.IntegerField()),
                ('special', models.BooleanField()),
                ('grad_type', models.CharField(max_length=20)),
            ],
        ),
    ]
