# Generated by Django 2.2.6 on 2019-10-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('course_number', models.IntegerField(unique=True)),
                ('subject', models.CharField(choices=[('CSIS', 'CSIS'), ('CSCI', 'CSCI'), ('INFO', 'INFO'), ('CIS', 'CIS')], max_length=20)),
                ('min_hours', models.IntegerField()),
                ('max_hours', models.IntegerField()),
                ('fixed_hours', models.IntegerField(default=0)),
                ('special', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=1)),
                ('grad_type', models.CharField(choices=[('UNGR', 'Undergraduate'), ('GRAD', 'Graduate')], max_length=20)),
            ],
        ),
    ]
