# Generated by Django 2.2.5 on 2019-09-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20190928_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='special',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1),
        ),
    ]
