# Generated by Django 2.2.5 on 2019-09-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20190928_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='special',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=1),
        ),
    ]
