# Generated by Django 2.2.5 on 2019-10-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20190928_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='fixed_hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
