# Generated by Django 2.2.5 on 2019-09-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_auto_20190929_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Rooms')),
            ],
        ),
    ]
