# Generated by Django 2.2.5 on 2019-09-30 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduled',
            old_name='room_number',
            new_name='room',
        ),
    ]
