# Generated by Django 2.2.5 on 2019-09-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0002_auto_20190930_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='room',
            field=models.IntegerField(),
        ),
    ]
