# Generated by Django 2.2.5 on 2019-09-30 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0004_scheduled_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Rooms'),
        ),
    ]
