# Generated by Django 2.2.5 on 2019-10-01 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20190928_2113'),
        ('scheduledClass', '0006_auto_20190930_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='banner_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='building',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='campus',
            field=models.CharField(default='M', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Classes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduled',
            name='crn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduled',
            name='delivery',
            field=models.CharField(default='TR', max_length=3),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='friday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='monday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='notes',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='offering',
            field=models.CharField(default=' ', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduled',
            name='primary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='saturday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='sunday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='thursday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='tuesday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='wednesday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Rooms'),
        ),
    ]
