# Generated by Django 2.2.5 on 2019-10-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0007_auto_20191001_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='crn',
            field=models.IntegerField(default=0),
        ),
    ]
