# Generated by Django 2.2.5 on 2019-10-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0008_auto_20191001_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='end_time',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='start_time',
            field=models.IntegerField(default=100),
        ),
    ]
