# Generated by Django 2.2.5 on 2019-10-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0009_auto_20191001_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled',
            name='banner_id',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='building',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='course',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='crn',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='offering',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='wednesday',
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='room',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
