# Generated by Django 2.2.5 on 2019-10-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0014_auto_20191001_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='test',
            field=models.IntegerField(default=1),
        ),
    ]
