# Generated by Django 2.2.5 on 2019-10-01 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20190928_2113'),
        ('scheduledClass', '0018_remove_scheduled_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Classes'),
            preserve_default=False,
        ),
    ]
