# Generated by Django 2.2.5 on 2019-10-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0019_scheduled_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='banner_id',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduled',
            name='crn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduled',
            name='flex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduled',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduled',
            name='offering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduled',
            name='primary',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
