# Generated by Django 2.2.5 on 2019-10-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0020_auto_20191001_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='friday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='monday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='saturday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='sunday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='thursday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='tuesday',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='wednesday',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
