# Generated by Django 2.2.5 on 2019-10-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0021_auto_20191001_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='monday',
            field=models.CharField(blank=True, choices=[('M', 'M')], max_length=1),
        ),
    ]
