# Generated by Django 2.2.5 on 2019-10-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0022_auto_20191001_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='friday',
            field=models.CharField(blank=True, choices=[('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='saturday',
            field=models.CharField(blank=True, choices=[('S', 'S')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='sunday',
            field=models.CharField(blank=True, choices=[('U', 'U')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='thursday',
            field=models.CharField(blank=True, choices=[('H', 'H')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='tuesday',
            field=models.CharField(blank=True, choices=[('T', 'T')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='wednesday',
            field=models.CharField(blank=True, choices=[('W', 'W')], max_length=1),
        ),
    ]
