# Generated by Django 2.2.5 on 2019-10-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0023_auto_20191001_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='building',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='campus',
            field=models.CharField(default='M', max_length=5),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='delivery',
            field=models.CharField(default='TR', max_length=2),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
