# Generated by Django 2.2.5 on 2019-10-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0024_auto_20191001_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='banner_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='primary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
