# Generated by Django 2.2.5 on 2019-10-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0026_scheduled_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='flex',
            field=models.IntegerField(default=1),
        ),
    ]
