# Generated by Django 2.2.5 on 2019-10-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0029_scheduled_attrubute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduled',
            old_name='attrubute',
            new_name='attribute',
        ),
    ]
