# Generated by Django 2.2.5 on 2019-10-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0030_auto_20191002_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled',
            name='attribute',
        ),
    ]
