# Generated by Django 2.2.5 on 2019-10-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0032_auto_20191010_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='end_time',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='start_time',
            field=models.IntegerField(blank=True),
        ),
    ]
