# Generated by Django 2.2.5 on 2019-10-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0033_auto_20191010_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='building',
            field=models.CharField(default='8', max_length=5),
        ),
    ]
