# Generated by Django 2.2.5 on 2019-10-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0037_auto_20191017_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
    ]
