# Generated by Django 2.2.5 on 2019-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0038_remove_semester_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
