# Generated by Django 2.2.5 on 2019-10-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledClass', '0039_semester_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
